# Generated by Django 5.2 on 2025-04-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hedgingspr',
            old_name='dueDate',
            new_name='duedate',
        ),
    ]
