# Generated by Django 5.2 on 2025-04-30 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trades', '0003_alter_hedgingspr_leg1_float'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hedgingspr',
            name='broker_charges',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='broker_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='charges_unit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='counterparty',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='credit_terms1',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='credit_terms2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='floating_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='paper',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='pricing_basis1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='pricing_basis2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='pricing_period_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='pricing_period_to',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='quantity_mt',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='settlement_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='settlement_due',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='settlement_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='traded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hedging_trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='traded_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='tran_ref_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hedgingspr',
            name='transaction_type',
            field=models.CharField(choices=[('Bought', 'Bought'), ('Sold', 'Sold')], max_length=10, null=True),
        ),
    ]
