# Generated by Django 5.2 on 2025-04-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trades', '0004_alter_hedgingspr_broker_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hedgingspr',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
