# Generated by Django 5.2 on 2025-05-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trades', '0006_buyertransactionspr_demsellertransactionspr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterimTransactionSPR',
        ),
        migrations.DeleteModel(
            name='BuyerTransactionSpr',
        ),
        migrations.DeleteModel(
            name='DemSellerTransactionSpr',
        ),
    ]
