from django.db import models

class InterimTransactionSPR(models.Model):
    tran_ref_no = models.CharField(max_length=15, blank=True, null=True)
    nomination_ref = models.CharField(max_length=200, blank=True, null=True)
    no_of_sellers = models.IntegerField(blank=True, null=True)
    no_of_load_ports = models.IntegerField(blank=True, null=True)
    no_of_buyers = models.IntegerField(blank=True, null=True)
    no_of_discharge_ports = models.IntegerField(blank=True, null=True)
    cargo_name = models.CharField(max_length=50, blank=True, null=True)
    vessel_name = models.CharField(max_length=50, blank=True, null=True)
    strategy_name = models.CharField(max_length=10, blank=True, null=True)
    delete_status = models.IntegerField(default=0)




class DemSellerTransactionSpr(models.Model):
    """
    Represents seller transaction details.
    """
    purchase_contract_id = models.CharField(max_length=200, blank=True, null=True)
    tran_ref_no = models.CharField(max_length=15)
    seller_name = models.CharField(max_length=100, blank=True, null=True)
    seller_term_spot = models.CharField(max_length=15, blank=True, null=True)
    seller_contract_ref = models.CharField(max_length=50, blank=True, null=True)
    seller_deal_date = models.DateField(blank=True, null=True)
    seller_term = models.CharField(max_length=50, blank=True, null=True)
    seller_port_name = models.CharField(max_length=50, blank=True, null=True)
    seller_loading_laycan_from = models.DateField(blank=True, null=True)
    seller_loading_laycan_to = models.DateField(blank=True, null=True)
    seller_loadport_agent = models.CharField(max_length=100, blank=True, null=True)
    seller_loadport_inspector = models.CharField(max_length=100, blank=True, null=True)
    seller_discharge_laycan_from = models.DateField(blank=True, null=True)
    seller_discharge_laycan_to = models.DateField(blank=True, null=True)
    seller_discharge_agent = models.CharField(max_length=100, blank=True, null=True)
    seller_discharge_inspector = models.CharField(max_length=100, blank=True, null=True)
    seller_narrowed_days = models.IntegerField(blank=True, null=True)
    seller_narrowed_date = models.DateField(blank=True, null=True)
    seller_bl_date = models.DateField(blank=True, null=True)
    seller_nor_date = models.DateField(blank=True, null=True)
    seller_estimated_bl_date = models.DateField(blank=True, null=True)
    seller_estimated_nor_date = models.DateField(blank=True, null=True)
    seller_contract_quantiity_mton_air = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    seller_contract_quantiity_barrels = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    seller_operational_tolerence = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    seller_oper_tol_option = models.CharField(max_length=50, blank=True, null=True)
    seller_bl_quantiity_mton_vac = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    loadedquality = models.CharField(max_length=25, blank=True, null=True)
    seller_bl_quantiity_mton_air = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    seller_bl_quantiity_barrels = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    seller_bl_quantiity_cubic_meters = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    seller_outturn_quantity_mtons_vac = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    seller_outturn_quantity_mton_air = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    seller_outturn_quantity_barrels = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    seller_outturn_quantity_cubic_meters = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    seller_pricing_unit = models.CharField(max_length=100, blank=True, null=True)
    seller_invoice_qtybasis = models.CharField(max_length=100, blank=True, null=True)
    seller_pricingbasis = models.CharField(max_length=100, blank=True, null=True)
    pricing_basis2 = models.CharField(max_length=100, blank=True, null=True)
    pricing_basis3 = models.CharField(max_length=100, blank=True, null=True)
    pricing_basis4 = models.CharField(max_length=100, blank=True, null=True)
    forward_group = models.CharField(max_length=200, blank=True, null=True)
    forward_name = models.CharField(max_length=200, blank=True, null=True)
    time_period = models.CharField(max_length=200, blank=True, null=True)
    seller_pricing_period_basis = models.CharField(max_length=100, blank=True, null=True)
    seller_pricing_quotes = models.CharField(max_length=10, blank=True, null=True)
    seller_premium_discount = models.CharField(max_length=10, blank=True, null=True)
    seller_price_rounded = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    seller_fixed_pricing_period_from = models.DateField(blank=True, null=True)
    seller_fixed_pricing_period_to = models.DateField(blank=True, null=True)
    seller_payment_terms = models.CharField(max_length=100, blank=True, null=True)
    seller_lc = models.CharField(max_length=10, blank=True, null=True)
    seller_lc_days = models.CharField(max_length=10, blank=True, null=True)
    seller_lc_laycan = models.CharField(max_length=100, blank=True, null=True)
    seller_credit = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    seller_credit_days = models.CharField(max_length=100, blank=True, null=True)
    seller_credit_option = models.CharField(max_length=10, blank=True, null=True)
    seller_weekend_clause = models.CharField(max_length=100, blank=True, null=True)
    seller_laytime_hours = models.IntegerField(blank=True, null=True)
    seller_anydeductions = models.CharField(max_length=100, blank=True, null=True)
    seller_contractual_quality = models.CharField(max_length=100, blank=True, null=True)
    seller_pricingperiodbasisholiday1 = models.IntegerField(blank=True, null=True)
    seller_pricingperiodbasisholiday2 = models.IntegerField(blank=True, null=True)
    seller_unit_price = models.CharField(max_length=30, blank=True, null=True)
    seller_invoice_qty = models.FloatField(blank=True, null=True)
    seller_invoice_value = models.CharField(max_length=30, blank=True, null=True)
    seller_due_date = models.DateField(blank=True, null=True)
    trigger_commence = models.DateField(blank=True, null=True)
    trigger_expiry = models.DateField(blank=True, null=True)
    d_discount = models.CharField(max_length=10, blank=True, null=True)
    triggered_on = models.DateField(blank=True, null=True)
    pip_date1 = models.DateField(blank=True, null=True)
    pip_date2 = models.DateField(blank=True, null=True)
    pif_date1 = models.DateField(blank=True, null=True)
    pif_date2 = models.DateField(blank=True, null=True)
    freight_port1 = models.CharField(max_length=100, blank=True, null=True)
    freight_port2 = models.CharField(max_length=100, blank=True, null=True)
    kp_rate = models.DateField(blank=True, null=True)
    kf_rate = models.DateField(blank=True, null=True)
    esc_base_density = models.CharField(max_length=10, blank=True, null=True)
    esc_deesc = models.CharField(max_length=10, blank=True, null=True)
    esc_contract_density = models.CharField(max_length=10, blank=True, null=True)
    esc_loaded_density = models.CharField(max_length=10, blank=True, null=True)
    ai_base_density = models.CharField(max_length=10, blank=True, null=True)
    kin_base_density = models.CharField(max_length=10, blank=True, null=True)
    kin_deesc = models.CharField(max_length=10, blank=True, null=True)
    kin_contract_density = models.CharField(max_length=10, blank=True, null=True)
    kin_loaded_density = models.CharField(max_length=10, blank=True, null=True)
    ai_deesc = models.CharField(max_length=10, blank=True, null=True)
    ai_contract_density = models.CharField(max_length=10, blank=True, null=True)
    ai_loaded_density = models.CharField(max_length=10, blank=True, null=True)
    t_freight = models.CharField(max_length=10, blank=True, null=True)
    prepayment = models.CharField(max_length=100, blank=True, null=True)
    prepayment_vol = models.CharField(max_length=10, blank=True, null=True)
    prepayment_discount = models.CharField(max_length=10, blank=True, null=True)
    prepayment_period1 = models.DateField(blank=True, null=True)
    prepayment_period2 = models.DateField(blank=True, null=None)
    prepayment_due_date = models.DateField(blank=True, null=None)
    euro_conv_date = models.DateField(blank=True, null=None)
    euro_conv = models.CharField(max_length=10, blank=True, null=None)
    esc_deesc1 = models.CharField(max_length=10, blank=True, null=None)
    kin_deesc1 = models.CharField(max_length=10, blank=True, null=None)
    ai_deesc1 = models.CharField(max_length=10, blank=True, null=None)
    gtc = models.CharField(max_length=50, blank=True, null=None)
    price_declared = models.DateField(blank=True, null=None)
    euro_conv_type = models.CharField(max_length=20, blank=True, null=None)
    euro_conv_month = models.CharField(max_length=20, blank=True, null=None)
    seller_pricing_quotes1 = models.CharField(max_length=30, blank=True, null=None)
    seller_payment_invoice = models.CharField(max_length=30, blank=True, null=None)
    seller_delivery_start = models.DateField(blank=True, null=None)
    seller_delivery_end = models.DateField(blank=True, null=None)
    cargo_name = models.CharField(max_length=100, blank=True, null=None)
    seller_contract_specific_gravity = models.CharField(max_length=15, blank=True, null=None)
    seller_loaded_specific_gravity = models.CharField(max_length=15, blank=True, null=None)
    date_created = models.DateTimeField()
    date_modified = models.DateTimeField()
    seller_price_calculation_density = models.CharField(max_length=15, blank=True, null=None)
    documentary_instructions_date = models.DateField(blank=True, null=None)
    voyage_orders_sent_on = models.DateField(blank=True, null=None)
    inspection_appointment_date = models.DateField(blank=True, null=None)
    insurance_instructions_date = models.DateField(blank=True, null=None)
    lc_format_date = models.DateField(blank=True, null=None)
    lc_received_on = models.DateField(blank=True, null=None)
    price_calculations_sent_on = models.DateField(blank=True, null=None)
    invoice_sent_on = models.DateField(blank=True, null=None)
    invoice_payment_received_on = models.DateField(blank=True, null=None)
    demurrage_calculations_date = models.DateField(blank=True, null=None)
    pricing_finalized = models.IntegerField(default=0)
    traded_by = models.CharField(max_length=300, blank=True, null=True)
    traded_on = models.CharField(max_length=15, blank=True, null=True)
    approved_by = models.CharField(max_length=300, blank=True, null=True)
    approved_on = models.CharField(max_length=15, blank=True, null=True)
    seller_provisional_payment = models.CharField(max_length=30, blank=True, null=True)
    seller_provisional_period_from = models.DateField(blank=True, null=True)
    seller_provisional_period_to = models.DateField(blank=True, null=True)
    seller_provisional_payment_value = models.CharField(max_length=30, blank=True, null=True)
    seller_provisional_premium_discount = models.CharField(max_length=30, blank=True, null=True)
    seller_provisional_due_date = models.DateField(blank=True, null=True)
    seller_provisional_invoice_value = models.CharField(max_length=30, blank=True, null=True)
    seller_provisional_invoice_payment_value = models.CharField(max_length=30, blank=True, null=True)
    transaction_status = models.CharField(max_length=200, blank=True, null=True)
    tradername = models.CharField(max_length=200, blank=True, null=True)
    counterparty_fef = models.CharField(max_length=200, blank=True, null=True)
    counterparties = models.CharField(max_length=200, blank=True, null=True)
    ctime = models.CharField(max_length=20, blank=True, null=True)
    ctime1 = models.CharField(max_length=20, blank=True, null=True)
    term_contract_ref_no = models.CharField(max_length=200, blank=True, null=True)
    term_contract_ref = models.CharField(max_length=200, blank=True, null=True)
    term_contract_lifting = models.CharField(max_length=200, blank=True, null=True)
    term_contract_lifting1 = models.CharField(max_length=200, blank=True, null=True)
    total_volume = models.CharField(max_length=200, blank=True, null=True)
    total_volume1a = models.CharField(max_length=200, blank=True, null=True)
    buyer_pricing_unita = models.CharField(max_length=200, blank=True, null=True)
    parcel_size = models.CharField(max_length=200, blank=True, null=True)
    parcel_size1 = models.CharField(max_length=200, blank=True, null=True)
    monthly_nomination = models.CharField(max_length=200, blank=True, null=True)
    nomination_changes = models.CharField(max_length=200, blank=True, null=True)
    parcel_sizea = models.CharField(max_length=200, blank=True, null=True)
    parcel_sizeb = models.CharField(max_length=200, blank=True, null=True)
    nquantity = models.CharField(max_length=200, blank=True, null=True)
    sent_on = models.DateField(blank=True, null=None)
    buyer_pricing_unita1 = models.CharField(max_length=200, blank=True, null=None)
    counterparty_fef1 = models.CharField(max_length=200, blank=True, null=None)
    accepted_on = models.DateField(blank=True, null=None)
    nomination_ref = models.CharField(max_length=200, blank=True, null=None)
    loadport = models.CharField(max_length=200, blank=True, null=None)
    seller_pricing_unita1 = models.CharField(max_length=200, blank=True, null=None)
    seller_pricing_unita = models.CharField(max_length=200, blank=True, null=None)
    transfer_title_date = models.DateField(blank=True, null=None)
    contract_counterparty = models.CharField(max_length=200, blank=True, null=None)
    destination = models.CharField(max_length=200, blank=True, null=None)
    destination_port = models.CharField(max_length=200, blank=True, null=None)
    nor_desination = models.DateField(blank=True, null=None)
    cargo_financial_hold = models.CharField(max_length=200, blank=True, null=None)
    accounting_period = models.CharField(max_length=200, blank=True, null=None)
    compleetion_dis_date = models.DateField(blank=True, null=None)
    freight_component = models.CharField(max_length=200, blank=True, null=None)
    seller_invoice_qtybasis1 = models.CharField(max_length=200, blank=True, null=None)
    seller_pricing_unit_1 = models.CharField(max_length=200, blank=True, null=None)
    laytime_hours = models.CharField(max_length=100, blank=True, null=None)
    demurrage_rate = models.CharField(max_length=100, blank=True, null=None)
    charterparty = models.CharField(max_length=100, blank=True, null=None)
    afra = models.CharField(max_length=100, blank=True, null=None)
    time_bar = models.CharField(max_length=100, blank=True, null=None)
    timebar_date = models.CharField(max_length=100, blank=True, null=None)
    percentage = models.CharField(max_length=100, blank=True, null=None)
    percentage1 = models.CharField(max_length=100, blank=True, null=None)

    
class BuyerTransactionSpr(models.Model):
    """
    Represents buyer transaction details.
    """
    sale_contract_id = models.CharField(max_length=200, blank=True, null=True)
    nomination_ref = models.CharField(max_length=200, blank=True, null=True)
    tran_ref_no = models.CharField(max_length=15, blank=True, null=True)
    buyer_name = models.CharField(max_length=100, blank=True, null=True)
    buyer_contract_ref = models.CharField(max_length=100, blank=True, null=True)
    buyer_deal_date = models.TextField(blank=True, null=True)
    buyer_term_spot = models.CharField(max_length=200, blank=True, null=True)
    buyer_term = models.CharField(max_length=200, blank=True, null=True)
    buyer_port_name = models.CharField(max_length=200, blank=True, null=True)
    buyer_loading_laycan_from = models.CharField(max_length=100, blank=True, null=True)
    buyer_loading_laycan_to = models.CharField(max_length=19, blank=True, null=True)
    buyer_loadport_agent = models.CharField(max_length=100, blank=True, null=True)
    buyer_loadport_inspector = models.CharField(max_length=100, blank=True, null=True)
    buyer_discharge_laycan_from = models.DateField(blank=True, null=True)
    buyer_discharge_laycan_to = models.DateField(blank=True, null=True)
    buyer_discharge_agent = models.CharField(max_length=100, blank=True, null=True)
    buyer_discharge_inspector = models.CharField(max_length=100, blank=True, null=True)
    buyer_narrowed_days = models.CharField(max_length=100, blank=True, null=True)
    buyer_narrowed_date = models.CharField(max_length=100, blank=True, null=True)
    buyer_bl_date = models.CharField(max_length=11, blank=True, null=True)
    buyer_nor_date = models.CharField(max_length=100, blank=True, null=True)
    buyer_estimated_bl_date = models.CharField(max_length=100, blank=True, null=True)
    buyer_estimated_nor_date = models.CharField(max_length=100, blank=True, null=True)
    buyer_contract_quantity_mton_air = models.DecimalField(max_digits=19, decimal_places=3, blank=True, null=True)
    buyer_contract_quantity_barrels = models.CharField(max_length=100, blank=True, null=True)
    buyer_operational_tolerance = models.CharField(max_length=100, blank=True, null=True)
    buyer_oper_tol_option = models.CharField(max_length=50, blank=True, null=True)
    buyer_bl_quantity_mton_vac = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    loaded_quality = models.CharField(max_length=25, blank=True, null=True)
    buyer_bl_quantity_mton_air = models.CharField(max_length=19, blank=True, null=True)
    buyer_bl_quantity_barrels = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    buyer_bl_quantity_cubic_meters = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    buyer_outturn_quantity_mtons_vac = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    buyer_outturn_quantity_mton_air = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    buyer_outturn_quantity_barrels = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    buyer_outturn_quantity_cubic_meters = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    buyer_pricing_unit = models.CharField(max_length=100, blank=True, null=True)
    buyer_invoice_qty_basis = models.CharField(max_length=100, blank=True, null=True)
    buyer_pricing_basis = models.CharField(max_length=100, blank=True, null=True)
    pricing_basis2 = models.CharField(max_length=100, blank=True, null=True)
    pricing_basis3 = models.CharField(max_length=100, blank=True, null=True)
    pricing_basis4 = models.CharField(max_length=100, blank=True, null=True)
    buyer_pricing_period_basis = models.CharField(max_length=100, blank=True, null=True)
    buyer_pricing_quotes = models.CharField(max_length=10, blank=True, null=True)
    buyer_premium_discount = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    buyer_price_rounded = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)
    buyer_fixed_pricing_period_from = models.DateField(blank=True, null=True)
    buyer_fixed_pricing_period_to = models.DateField(blank=True, null=True)
    buyer_payment_terms = models.CharField(max_length=100, blank=True, null=True)
    buyer_lc = models.CharField(max_length=10, blank=True, null=True)
    buyer_lc_days = models.CharField(max_length=100, blank=True, null=True)
    buyer_lc_laycan = models.CharField(max_length=100, blank=True, null=True)
    buyer_credit = models.CharField(max_length=10, blank=True, null=True)
    buyer_credit_days = models.CharField(max_length=100, blank=True, null=True)
    buyer_credit_option = models.CharField(max_length=100, blank=True, null=True)
    buyer_weekend_clause = models.CharField(max_length=100, blank=True, null=True)
    buyer_laytime_hours = models.IntegerField(blank=True, null=True)
    buyer_any_deductions = models.CharField(max_length=100, blank=True, null=True)
    buyer_contractual_quality = models.CharField(max_length=100, blank=True, null=True)
    buyer_pricing_period_basis_holiday1 = models.IntegerField(blank=True, null=True)
    buyer_pricing_period_basis_holiday2 = models.IntegerField(blank=True, null=True)
    buyer_due_date = models.DateField(blank=True, null=True)
    buyer_unit_price = models.CharField(max_length=30, blank=True, null=True)
    buyer_invoice_qty = models.FloatField(blank=True, null=True)
    buyer_invoice_value = models.CharField(max_length=30, blank=True, null=True)
    buyer_trigger_commence = models.DateField(blank=True, null=True)
    buyer_trigger_expiry = models.DateField(blank=True, null=True)
    buyer_d_discount = models.CharField(max_length=10, blank=True, null=True)
    buyer_triggered_on = models.DateField(blank=True, null=True)
    buyer_pip_date1 = models.DateField(blank=True, null=True)
    buyer_pip_date2 = models.DateField(blank=True, null=True)
    buyer_pif_date1 = models.DateField(blank=True, null=True)
    buyer_pif_date2 = models.DateField(blank=True, null=True)
    buyer_freight_port1 = models.CharField(max_length=100, blank=True, null=True)
    buyer_freight_port2 = models.CharField(max_length=100, blank=True, null=True)
    buyer_kp_rate = models.DateField(blank=True, null=True)
    buyer_kf_rate = models.DateField(blank=True, null=True)
    buyer_esc_base_density = models.CharField(max_length=10, blank=True, null=True)
    buyer_esc_deesc = models.CharField(max_length=10, blank=True, null=True)
    buyer_esc_contract_density = models.CharField(max_length=10, blank=True, null=True)
    buyer_esc_loaded_density = models.CharField(max_length=10, blank=True, null=True)
    buyer_ai_base_density = models.CharField(max_length=10, blank=True, null=True)
    buyer_kin_base_density = models.CharField(max_length=10, blank=True, null=True)
    buyer_kin_deesc = models.CharField(max_length=10, blank=True, null=True)
    buyer_kin_contract_density = models.CharField(max_length=10, blank=True, null=True)
    buyer_kin_loaded_density = models.CharField(max_length=10, blank=True, null=True)
    buyer_ai_deesc = models.CharField(max_length=10, blank=True, null=True)
    buyer_ai_contract_density = models.CharField(max_length=10, blank=True, null=True)
    buyer_ai_loaded_density = models.CharField(max_length=10, blank=True, null=True)
    buyer_t_freight = models.CharField(max_length=10, blank=True, null=True)
    buyer_prepayment = models.CharField(max_length=10, blank=True, null=True)
    buyer_prepayment_vol = models.CharField(max_length=10, blank=True, null=True)
    buyer_prepayment_period1 = models.DateField(blank=True, null=True)
    buyer_prepayment_period2 = models.DateField(blank=True, null=True)
    buyer_prepayment_due_date = models.DateField(blank=True, null=True)
    buyer_euro_conv_date = models.DateField(blank=True, null=True)
    buyer_euro_conv = models.CharField(max_length=10, blank=True, null=True)
    buyer_esc_deesc1 = models.CharField(max_length=10, blank=True, null=True)
    buyer_kin_deesc1 = models.CharField(max_length=10, blank=True, null=True)
    buyer_ai_deesc1 = models.CharField(max_length=10, blank=True, null=True)
    buyer_prepayment_discount = models.CharField(max_length=10, blank=True, null=True)
    buyer_gtc = models.CharField(max_length=20, blank=True, null=True)
    buyer_price_declared = models.DateField(blank=True, null=True)
    buyer_euro_conv_month = models.CharField(max_length=20, blank=True, null=True)
    buyer_euro_conv_type = models.CharField(max_length=50, blank=True, null=True)
    buyer_pricing_quotes1 = models.CharField(max_length=30, blank=True, null=True)
    buyer_payment_invoice = models.CharField(max_length=30, blank=True, null=True)
    buyer_delivery_start = models.DateField(blank=True, null=True)
    buyer_delivery_end = models.DateField(blank=True, null=True)
    buyer_contract_specific_gravity = models.CharField(max_length=15, blank=True, null=True)
    buyer_loaded_specific_gravity = models.CharField(max_length=15, blank=True, null=True)
    cargo_name = models.CharField(max_length=100, blank=True, null=True)
    buyer_price_calculation_density = models.CharField(max_length=15, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True)
    date_modified = models.DateTimeField(blank=True, null=True)
    documentary_instructions_date = models.DateField(blank=True, null=True)
    voyage_orders_sent_on = models.DateField(blank=True, null=True)
    inspection_appointment_date = models.DateField(blank=True, null=True)
    insurance_instructions_date = models.DateField(blank=True, null=True)
    lc_format_date = models.DateField(blank=True, null=True)
    lc_received_on = models.DateField(blank=True, null=True)
    price_calculations_sent_on = models.DateField(blank=True, null=True)
    invoice_sent_on = models.DateField(blank=True, null=True)
    invoice_payment_received_on = models.DateField(blank=True, null=True)
    demurrage_calculations_date = models.DateField(blank=True, null=True)
    pricing_finalized = models.IntegerField(blank=True, null=True)
    traded_by = models.CharField(max_length=300, blank=True, null=True)
    traded_on = models.CharField(max_length=15, blank=True, null=True)
    approved_by = models.CharField(max_length=300, blank=True, null=True)
    approved_on = models.CharField(max_length=15, blank=True, null=True)
    buyer_provisional_payment = models.CharField(max_length=30, blank=True, null=True)
    buyer_provisional_period_from = models.DateField(blank=True, null=True)
    buyer_provisional_period_to = models.DateField(blank=True, null=True)
    buyer_provisional_payment_value = models.CharField(max_length=30, blank=True, null=True)
    buyer_provisional_premium_discount = models.CharField(max_length=30, blank=True, null=True)
    buyer_provisional_due_date = models.DateField(blank=True, null=True)
    buyer_provisional_invoice_value = models.CharField(max_length=30, blank=True, null=True)
    buyer_provisional_invoice_payment_value = models.CharField(max_length=30, blank=True, null=True)
    transaction_status = models.CharField(max_length=200, blank=True, null=True)
    trader_name = models.CharField(max_length=200, blank=True, null=True)
    counterparty_fef = models.CharField(max_length=200, blank=True, null=True)
    counterparties = models.CharField(max_length=200, blank=True, null=True)
    term_contract_ref_no = models.CharField(max_length=200, blank=True, null=True)
    term_contract_ref = models.CharField(max_length=200, blank=True, null=True)
    term_contract_lifting = models.CharField(max_length=200, blank=True, null=True)
    term_contract_lifting1 = models.CharField(max_length=200, blank=True, null=True)
    total_volume = models.CharField(max_length=200, blank=True, null=True)
    total_volume1a = models.CharField(max_length=200, blank=True, null=True)
    buyer_pricing_unita = models.CharField(max_length=200, blank=True, null=True)
    parcel_size = models.CharField(max_length=200, blank=True, null=True)
    parcel_size1 = models.CharField(max_length=200, blank=True, null=True)
    monthly_nomination = models.CharField(max_length=200, blank=True, null=True)
    nomination_changes = models.CharField(max_length=200, blank=True, null=True)
    parcel_sizea = models.CharField(max_length=200, blank=True, null=True)
    parcel_sizeb = models.CharField(max_length=200, blank=True, null=True)
    nquantity = models.CharField(max_length=200, blank=True, null=True)
    sent_on = models.DateField(blank=True, null=True)
    buyer_pricing_unita1 = models.CharField(max_length=200, blank=True, null=True)
    counterparty_fef1 = models.CharField(max_length=200, blank=True, null=True)
    accepted_on = models.DateField(blank=True, null=True)
    ctime = models.CharField(max_length=20, blank=True, null=True)
    ctime1 = models.CharField(max_length=20, blank=True, null=True)
    loadport = models.CharField(max_length=200, blank=True, null=True)
    transfer_title_date = models.DateField(blank=True, null=True)
    contract_counterparty = models.CharField(max_length=200, blank=True, null=True)
    destination = models.CharField(max_length=200, blank=True, null=True)
    destination_port = models.CharField(max_length=200, blank=True, null=True)
    nor_destination = models.DateField(blank=True, null=True)
    cargo_financial_hold = models.CharField(max_length=200, blank=True, null=True)
    accounting_period = models.CharField(max_length=200, blank=True, null=True)
    completion_dis_date = models.DateField(blank=True, null=True)
    freight_component = models.CharField(max_length=200, blank=True, null=True)
    buyer_invoice_qty_basis1 = models.CharField(max_length=200, blank=True, null=True)
    buyer_pricing_unit1 = models.CharField(max_length=200, blank=True, null=True)
    buyer_pricing_unit_1 = models.CharField(max_length=200, blank=True, null=True)
    portfolio = models.CharField(max_length=200, blank=True, null=True)
    group_name = models.CharField(max_length=200, blank=True, null=True)
    buyer_pv_ref_no = models.CharField(max_length=200, blank=True, null=True)
    buyer_pv_date = models.DateField(blank=True, null=True)
    remaining = models.CharField(max_length=200, blank=True, null=True)
    esc_de_esc_value = models.CharField(max_length=200, blank=True, null=True)
    period_from = models.DateField(blank=True, null=True)
    period_to = models.DateField(blank=True, null=True)
    inv_per = models.CharField(max_length=10, blank=True, null=True)
